export enum ErrorCode {
    MISSING_REQUIRED,
    INVALID_DATA,
    INVALID_TYPE,
    INVALID_JSON,
    INVALID_EMAIL,
    EMAIL_EXISTS,
    PASSWORD_REQUIREMENTS,
    PASSWORD_COMMON,
    NOT_FOUND_ACCOUNT,
    UNKOWN
};